# Generated by Django 3.2.4 on 2021-06-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingstock',
            name='number_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incomingstock',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sale',
            name='qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='in_stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
