# Generated by Django 3.2.4 on 2021-06-22 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stock_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='category',
            new_name='category_id',
        ),
    ]
